name: tests

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib --bins --examples --tests --benches
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib --bins --examples --tests --benches --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-default-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=colored
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=syslog-3
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=syslog-4
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=syslog-6
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=reopen-03
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=reopen-1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features=meta-logging-in-format
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - run: cargo run --example cmd-program
      - run: cargo run --example cmd-program -- --verbose
      - run: cargo run --example colored --features colored
      - run: cargo run --example pretty-colored --features colored
      - run: cargo run --example date-based-file-log --features date-based
      # we don't exactly have a good test suite for DateBased right now, so let's at least do this:
      - run: cargo run --example date-based-file-log --features date-based,meta-logging-in-format
      - run: cargo doc --all-features
        env:
          RUSTDOCFLAGS: -D warnings
  linux:
    name: Linux-only Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo run --example syslog3 --features syslog-3
      - run: cargo run --example syslog4 --features syslog-4
      - run: cargo run --example syslog --features syslog-6
  test:
    name: MSRV Compatability: Core
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.31.0
          override: true
      - run: cargo build
      - run: cargo build --features reopen-1,reopen-03,meta-logging-in-format,syslog-3
  msrv_date_based:
    name: MSRV Compatability: date-based
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.48.0
          override: true
      - run: cargo build --features date-based
  msrv_syslog_4:
    name: MSRV Compatability: syslog-4
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.51.0
          override: true
      - run: cargo build --features syslog-4
  msrv_syslog_6:
    name: MSRV Compatability: syslog-6
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.59.0
          override: true
      - run: cargo build --features syslog-4,syslog-6
